### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by akien-mga** [h00g3/midnightbadminton#7]
Congrats on the release! Rémi here :)

As there's no `LICENSE` or `LICENSE.txt` file describing the licensing information for the released code and assets, this is proprietary by default, even if the source is shared. If you wish to make this an open source project to which others can collaborate, you should add a license document that tells contributors under which term they and others can use the code.

https://choosealicense.com/ has useful information to make that choice and see how to apply the license (note that defining a license requires consent from all copyright holders, which might be either each developer/artist or the ORF depending on what terms you got internally).

Note that it's also possible to have different licenses for the code/scenes and the art assets, if relevant. I'm happy to advise if needed :)

**Comment by h00g3** [comment]
Thank you, I added a license which I hope more or less fits the case ;)
